Help on AuthError in module src.auth.auth object:

class AAuutthhEErrrroorr(exceptions.Exception)
 |  Method resolution order:
 |      AuthError
 |      exceptions.Exception
 |      exceptions.BaseException
 |      __builtin__.object
 |  
 |  Methods defined here:
 |  
 |  ____iinniitt____(self, error, status_code)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  ____wweeaakkrreeff____
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from exceptions.Exception:
 |  
 |  ____nneeww____ = <built-in method __new__ of type object>
 |      T.__new__(S, ...) -> a new object with type S, a subtype of T
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from exceptions.BaseException:
 |  
 |  ____ddeellaattttrr____(...)
 |      x.__delattr__('name') <==> del x.name
 |  
 |  ____ggeettaattttrriibbuuttee____(...)
 |      x.__getattribute__('name') <==> x.name
 |  
 |  ____ggeettiitteemm____(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  ____ggeettsslliiccee____(...)
 |      x.__getslice__(i, j) <==> x[i:j]
 |      
 |      Use of negative indices is not supported.
 |  
 |  ____rreedduuccee____(...)
 |  
 |  ____rreepprr____(...)
 |      x.__repr__() <==> repr(x)
 |  
 |  ____sseettaattttrr____(...)
 |      x.__setattr__('name', value) <==> x.name = value
 |  
 |  ____sseettssttaattee____(...)
 |  
 |  ____ssttrr____(...)
 |      x.__str__() <==> str(x)
 |  
 |  ____uunniiccooddee____(...)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from exceptions.BaseException:
 |  
 |  ____ddiicctt____
 |  
 |  aarrggss
 |  
 |  mmeessssaaggee
